server:
  port: 8080
  servlet:
    context-path: /identity
spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://DESKTOP-KR6P5K8\SQLEXPRESS:1433;databaseName=CourseManagementDB;encrypt=true;trustServerCertificate=true
    username: sManager
    password: 123456

  jpa:
    hibernate:
      ddl-auto: none
      naming:
        # 1. Implicit Strategy
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        # 2. Physical Strategy
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

jwt:
   signerKey: "ede507cf57e059ce241879a4ed896acc223fb9a4790feb814db91946ef9fcde9"